package com.example.monpotager.models;

import static androidx.room.ForeignKey.CASCADE;

import androidx.annotation.NonNull;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.Index;
import androidx.room.PrimaryKey;

import com.example.monpotager.models.Parcelle;

/**
 * Entity Class for an Action
 */
@Entity(tableName = "action_table",
        foreignKeys = @ForeignKey(entity = Parcelle.class,

        parentColumns = "id",

        childColumns = "parcelleId"))
public class Action {
    /**
     * Id of the Action, autogenerated
     */
    @PrimaryKey(autoGenerate = true)
    private long id;

    /**
     * Id of the parcelle where the Action was made
     */
    private long parcelleId;

    /**
     * Type of the Action (for instance "Arroser")
     */
    private String type;

    /**
     * Date of the Action (DD/MM/YYYY)
     */
    private String date;

    /**
     * Description of the Action
     */
    private String description;

    /**
     * Default Constructor
     */
    public Action() { }

    /**
     * Constructor with parameters
     * @param parcelleId
     * @param type
     * @param date
     * @param description
     */
    public Action(long parcelleId, String type, String date, String description) {

        this.parcelleId = parcelleId;

        this.type = type;

        this.date = date;

        this.description = description;

    }

    // --- GETTERS ---

    public long getId() { return id; }

    public String getType() { return type; }

    public String getDate() { return date; }

    public String getDescription() { return description; }

    public long getParcelleId() { return parcelleId; }

    // --- SETTERS ---

    public void setId(long id) { this.id = id; }

    public void setType(String nom) { this.type = nom; }

    public void setDate(String date) { this.date = date; }

    public void setDescription(String text) { this.description = text; }

    public void setParcelleId(long parcelleId) { this.parcelleId = parcelleId; }

}
